export default [
  {
    cat: "technology",
    name: "Kafka",
    value: 20,
    icon: "./kafka.png",
    url: "https://kafka.apache.org/",
  },
  {
    cat: "language",
    name: "Golang",
    value: 50,
    icon: "./golang.png",
    url: "https://golang.org/",
  },
  {
    cat: "technology",
    name: "NodeJS",
    value: 10,
    icon: "./nodejs.svg",
    url: "https://nodejs.org/en/",
  },
  {
    cat: "framework",
    name: "Seldon Core",
    value: 20,
    icon: "./seldon.png",
    url: "https://github.com/SeldonIO/seldon-core/",
  },
  {
    cat: "framework",
    name: "D3",
    value: 20,
    icon: "./d3.svg",
    url: "https://d3js.org/",
  },
  {
    cat: "framework",
    name: "ReactJS",
    value: 20,
    icon: "./react.png",
    url: "https://reactjs.org/",
  },
  {
    cat: "technology",
    name: "ElasticSearch",
    value: 30,
    icon: "./elasticsearch.png",
    url: "https://www.elastic.co/",
  },
  {
    cat: "framework",
    name: "Alibi Detect",
    value: 20,
    icon: "./alibi-detect.png",
    url: "https://github.com/SeldonIO/alibi-detect",
  },
  {
    cat: "technology",
    name: "Docker",
    value: 30,
    icon: "./docker.svg",
    url: "https://www.docker.com/",
  },
  {
    cat: "language",
    name: "HTML5 & CSS3",
    value: 30,
    icon: "./html5-css3.png",
    url: "https://developer.mozilla.org/kab/docs/Web/HTML",
  },
  {
    cat: "technology",
    name: "MLServer",
    value: 20,
    icon: "./mlserver.png",
    url: "https://github.com/SeldonIO/MLServer",
  },
  {
    cat: "language",
    name: "Python",
    value: 20,
    icon: "./python.png",
    url: "https://www.python.org/",
  },
  {
    cat: "language",
    name: "Elixir",
    value: 5,
    icon: "./elixir.png",
    url: "https://elixir-lang.org/",
  },
  {
    cat: "technology",
    name: "Triton",
    value: 20,
    icon: "./triton.png",
    url: "https://developer.nvidia.com/nvidia-triton-inference-server",
  },
  {
    cat: "technology",
    name: "Kubernetes",
    value: 40,
    icon: "./k8s.png",
    url: "https://kubernetes.io/",
  },
  {
    cat: "language",
    name: "MATLAB",
    value: 10,
    icon: "./matlab.png",
    url: "https://www.mathworks.com/products/matlab.html",
  },
  {
    cat: "technology",
    name: "Prometheus",
    value: 30,
    icon: "./prometheus.png",
    url: "https://prometheus.io/",
  },
  {
    cat: "framework",
    name: "Tensorflow",
    value: 20,
    icon: "./tf.png",
    url: "https://js.tensorflow.org/",
  },
  {
    cat: "technology",
    name: "Postgres",
    value: 30,
    icon: "./postgres.png",
    url: "https://www.postgresql.org/",
  },
  {
    cat: "technology",
    name: "GitOps",
    value: 10,
    icon: "./git.png",
    url: "https://git-scm.com/",
  },
  {
    cat: "technology",
    name: "Jupyter",
    value: 20,
    icon: "./jupyter.png",
    url: "https://jupyter.org/",
  },
  {
    cat: "technology",
    name: "Raspberry Pi",
    value: 5,
    icon: "./raspberry.png",
    url: "https://www.raspberrypi.org/",
  },
  {
    cat: "framework",
    name: "Apache Pinot",
    value: 20,
    icon: "./pinot.svg",
    url: "https://pinot.apache.org/",
  },
  {
    cat: "framework",
    name: "Kubeflow",
    value: 10,
    icon: "./kubeflow.jpg",
    url: "https://www.kubeflow.org/",
  },
];
